#!/bin/bash
while [ true ]
do
########### get alert Data##############
declare -i cnt=0 
lynx -dump $1  | sed -n "/$2/,/Display/p" | sed "1,/$3:/!d"  | sed '1d;$d'  > /tmp/w.buf
# lynx -dump $1  | sed -n '/Weather warnings/,/Display/p' | sed '1,/Caption:/!d'  | sed '1d;$d' > w.buf
input="$(cat /tmp/w.buf | grep .jpg )"
#echo $input
while IFS= read -r LINE
do
################## extracts alerts ################

SPLIT="$(echo $LINE | tr -d '[]' | tr -d '[:space:]')"

cat /tmp/w.buf | sed -n "/$SPLIT/, $ p" | head -3 | sed '1d;2d' | rev | cut -f1 -d":" |rev > /tmp/tmp.w  


input2="$(cat /tmp/tmp.w)"
if [ -z "$input2" ]
then
      echo "No Alert found"
else

############## process alerts ################

echo $input2 
if [ $input2 == Yellow ]
then
mpg123 YELLOW.mp3
mpg123 skills/meteo-alerts-skill/YELLOW.mp3
fi
if [ $input2 == Orange ]
then
mpg123 ORANGE.mp3
mpg123 skills/meteo-alerts-skill/ORANGE.mp3
fi
if [ $input2 == Red ]
then
mpg123 RED.mp3
mpg123 skills/meteo-alerts-skill/RED.mp3
fi
fi
done  <<< "$input"

   sleep 600
   echo next cycle
done
